server:
  port: 8089
  servlet:
    context-path: "/api"

spring:
  servlet:
    multipart:
      max-file-size: 30Mb
      max-request-size: 100Mb
      enabled: true
  datasource:
    name: test
    url: jdbc:mysql://116.62.130.69:3306/xy?useUnicode=true&characterEncoding=utf8
    username: root
    password: Gcb199107230513?
    # druid 连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.sptwin.xy.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
#自定义属性
contract:
  file-path: /home/xy/contract/contract.json
swagger:
  base-package: com.sptwin.xy.controller
user:
  default:
    pwd: abc123
excel:
  access:
    key: xy@excel